package modelosBD;
// Generated 02/10/2016 11:46:09 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Seriefavorita generated by hbm2java
 */
@Entity
@Table(name = "SERIEFAVORITA", catalog = "netxing")
public class SerieFavorita implements java.io.Serializable {

	private Integer idSerieFavorita;
	private Serie serie;
	private Usuario usuario;

	public SerieFavorita() {
	}

	public SerieFavorita(Serie serie, Usuario usuario) {
		this.serie = serie;
		this.usuario = usuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSerieFavorita", unique = true, nullable = false)
	public Integer getIdSerieFavorita() {
		return this.idSerieFavorita;
	}

	public void setIdSerieFavorita(Integer idSerieFavorita) {
		this.idSerieFavorita = idSerieFavorita;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERIE_idSerie", nullable = false)
	public Serie getSerie() {
		return this.serie;
	}

	public void setSerie(Serie serie) {
		this.serie = serie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUARIO_idUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
