package modelosBD;
// Generated 02/10/2016 11:46:09 by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Serie generated by hbm2java
 */
@Entity
@Table(name = "SERIE", catalog = "netxing")
public class Serie implements java.io.Serializable {

	private Integer idSerie;
	private String nome;
	private Set<Video> videos = new HashSet<Video>(0);
	private Set<SerieFavorita> seriefavoritas = new HashSet<SerieFavorita>(0);

	public Serie() {
	}

	public Serie(String nome) {
		this.nome = nome;
	}

	public Serie(String nome, Set<Video> videos, Set<SerieFavorita> seriefavoritas) {
		this.nome = nome;
		this.videos = videos;
		this.seriefavoritas = seriefavoritas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSerie", unique = true, nullable = false)
	public Integer getIdSerie() {
		return this.idSerie;
	}

	public void setIdSerie(Integer idSerie) {
		this.idSerie = idSerie;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serie")
	public Set<Video> getVideos() {
		return this.videos;
	}

	public void setVideos(Set<Video> videos) {
		this.videos = videos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serie")
	public Set<SerieFavorita> getSeriefavoritas() {
		return this.seriefavoritas;
	}

	public void setSeriefavoritas(Set<SerieFavorita> seriefavoritas) {
		this.seriefavoritas = seriefavoritas;
	}

}
