package modelosBD;
// Generated 02/10/2016 11:46:09 by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIO", catalog = "netxing")
public class Usuario implements java.io.Serializable {

	private int idUsuario;
	private String login;
	private String senha;
	private int idade;
	private Set<SerieFavorita> seriefavoritas = new HashSet<SerieFavorita>(0);
	private Set<VideoFavorito> videofavoritos = new HashSet<VideoFavorito>(0);

	public Usuario() {
	}

	public Usuario(int idUsuario, String login, String senha, int idade) {
		this.idUsuario = idUsuario;
		this.login = login;
		this.senha = senha;
		this.idade = idade;
	}

	public Usuario(int idUsuario, String login, String senha, int idade, Set<SerieFavorita> seriefavoritas,
			Set<VideoFavorito> videofavoritos) {
		this.idUsuario = idUsuario;
		this.login = login;
		this.senha = senha;
		this.idade = idade;
		this.seriefavoritas = seriefavoritas;
		this.videofavoritos = videofavoritos;
	}

	@Id

	@Column(name = "idUsuario", unique = true, nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "login", nullable = false, length = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "senha", nullable = false, length = 45)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@Column(name = "idade", nullable = false)
	public int getIdade() {
		return this.idade;
	}

	public void setIdade(int idade) {
		this.idade = idade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<SerieFavorita> getSeriefavoritas() {
		return this.seriefavoritas;
	}

	public void setSeriefavoritas(Set<SerieFavorita> seriefavoritas) {
		this.seriefavoritas = seriefavoritas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<VideoFavorito> getVideofavoritos() {
		return this.videofavoritos;
	}

	public void setVideofavoritos(Set<VideoFavorito> videofavoritos) {
		this.videofavoritos = videofavoritos;
	}

}
